### ISSUE TITLE
Class au.com.bytecode.opencsv.CSVReader does not implement the requested interface java.lang.AutoCloseable

### ISSUE THREAD

**Issue by faxiubite** [lwhite1/tablesaw#71] opened 2016-07-24 08:01 UTC
Exception in thread "main" java.lang.IncompatibleClassChangeError: Class au.com.bytecode.opencsv.CSVReader does not implement the requested interface java.lang.AutoCloseable
	at com.github.lwhite1.tablesaw.io.csv.CsvReader.$closeResource(CsvReader.java:141)
	at com.github.lwhite1.tablesaw.io.csv.CsvReader.detectColumnTypes(CsvReader.java:376)
	at com.github.lwhite1.tablesaw.io.csv.CsvReader.read(CsvReader.java:90)
	at com.github.lwhite1.tablesaw.api.Table.createFromCsv(Table.java:702)
note：
jdk Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

**Comment by faxiubite** [comment] 2016-07-24 12:40
I also tried JDK1.7 
the same issue

**Comment by lwhite1** [comment] 2016-07-24 12:53
Hmm. Seems like something the compiler should catch. I will look into it today.

**Comment by lwhite1** [comment] 2016-07-24 13:54
I'm afraid I don't have a great answer for you currently. 
I looked at OpenCSV. The version that I'm using (2.3) is out of date, but does implement Closeable.
I upgraded to 3.8, which has a different mvn group id, which is why i didn't notice it earlier.

When I run createFromCsv it works as expected with both the old OpenCSV and the new one.

After looking at the error message and googling around, I believe what is happening is that there is an older compiled version of a library that is being substituted at runtime in your environment. I'm not sure, but my guess is that it's an older version of Tablesaw. I suppose it could also be an older version of OpenCSV.

Here are some things to consider/try:

* Are you using a compiled Tablesaw jar in your build? If so, it should be refreshed from master and rebuilt. 
* Check what version of Tablesaw is included in your pom. If you installed a version in your local mvn repo, make sure that both the pom and the version in the repo are up to date.

If you're still stuck lmk and I can try to think of something else, but I'll probably need more info about your environment.

**Comment by faxiubite** [comment] 2016-07-25 02:31
thank you very much，

I download the jar from the sit mvn repository: http://www.mvnrepository.com/artifact/com.github.lwhite1/tablesaw

my env info：
I hava tried both jdk 1.7 and jdk 1.8 
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
I also tried version 0.7 and 0.71 
it's the same issue,
is there any other info you need ？

**Comment by lwhite1** [comment] 2016-07-26 00:00
Hi faxiubite,

I'm really very sorry that you're having difficulty, but I don't believe I can do much more unless you can share your project with me on github. (Even then, I'm not entirely sure I can help, but I will take a look)

Although the original cause was probably an incompatible change made between versions of Tablesaw, there is no change I can make to Tablesaw now to resolve it. It has to be fixed by a change to your project's dependencies.

The issue is that a library has changed and your project is using a pre-compiled version that is out of date. See this issue on StackOverflow:
http://stackoverflow.com/questions/1980452/what-causes-java-lang-incompatibleclasschangeerror.  

With pre-release code like Tablesaw, incompatible changes between versions are a necessary evil. 

You may want to consider using Maven to manage dependencies rather than working with compiled jars. I made the switch myself years ago and it makes everything easier.

**Closed** 2016-08-01 12:23 UTC

**Comment by faxiubite** [comment] 2016-08-22 12:17
`````
If you must work with jars, the only thing I can suggest is to clone Tablesaw using git, and run: mvn clean install. You can then get the tablesaw-0.7.2-SNAPSHOT.jar from the target sub-directory and add that to your project manually.
`````
it worked, 
sorry for comment later
thank you

**Comment by lwhite1** [comment] 2016-08-22 13:59
No problem. Really glad you were able to get it to work.
